# coding: utf-8

# flake8: noqa

"""
    ComicBagi

    Comic hosting catalog provider.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.0.1"

# import apis into sdk package
from comicbagi_openapi.api.comic_api import ComicApi
from comicbagi_openapi.api.comic_chapter_api import ComicChapterApi
from comicbagi_openapi.api.language_api import LanguageApi
from comicbagi_openapi.api.link_api import LinkApi
from comicbagi_openapi.api.website_api import WebsiteApi

# import ApiClient
from comicbagi_openapi.api_response import ApiResponse
from comicbagi_openapi.api_client import ApiClient
from comicbagi_openapi.configuration import Configuration
from comicbagi_openapi.exceptions import OpenApiException
from comicbagi_openapi.exceptions import ApiTypeError
from comicbagi_openapi.exceptions import ApiValueError
from comicbagi_openapi.exceptions import ApiKeyError
from comicbagi_openapi.exceptions import ApiAttributeError
from comicbagi_openapi.exceptions import ApiException

# import models into sdk package
from comicbagi_openapi.models.comic import Comic
from comicbagi_openapi.models.comic_chapter import ComicChapter
from comicbagi_openapi.models.comic_chapter_provider import ComicChapterProvider
from comicbagi_openapi.models.comic_provider import ComicProvider
from comicbagi_openapi.models.error import Error
from comicbagi_openapi.models.language import Language
from comicbagi_openapi.models.link import Link
from comicbagi_openapi.models.new_comic import NewComic
from comicbagi_openapi.models.new_comic_chapter import NewComicChapter
from comicbagi_openapi.models.new_comic_chapter_provider import NewComicChapterProvider
from comicbagi_openapi.models.new_comic_provider import NewComicProvider
from comicbagi_openapi.models.new_language import NewLanguage
from comicbagi_openapi.models.new_link import NewLink
from comicbagi_openapi.models.new_website import NewWebsite
from comicbagi_openapi.models.set_comic import SetComic
from comicbagi_openapi.models.set_comic_chapter import SetComicChapter
from comicbagi_openapi.models.set_comic_chapter_provider import SetComicChapterProvider
from comicbagi_openapi.models.set_comic_provider import SetComicProvider
from comicbagi_openapi.models.set_language import SetLanguage
from comicbagi_openapi.models.set_link import SetLink
from comicbagi_openapi.models.set_website import SetWebsite
from comicbagi_openapi.models.website import Website
