# coding: utf-8

"""
    ComicBagi

    Comic hosting catalog provider.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicbagi_openapi.models.set_comic_chapter_provider import SetComicChapterProvider

class TestSetComicChapterProvider(unittest.TestCase):
    """SetComicChapterProvider unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetComicChapterProvider:
        """Test SetComicChapterProvider
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetComicChapterProvider`
        """
        model = SetComicChapterProvider()
        if include_optional:
            return SetComicChapterProvider(
                link_website_host = '',
                link_relative_reference = '',
                language_lang = '',
                released_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return SetComicChapterProvider(
        )
        """

    def testSetComicChapterProvider(self):
        """Test SetComicChapterProvider"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
