# coding: utf-8

"""
    ComicBagi

    Comic hosting catalog provider.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicbagi_openapi.api.comic_api import ComicApi


class TestComicApi(unittest.TestCase):
    """ComicApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ComicApi()

    def tearDown(self) -> None:
        pass

    def test_add_comic(self) -> None:
        """Test case for add_comic

        Add comic.
        """
        pass

    def test_add_comic_provider(self) -> None:
        """Test case for add_comic_provider

        Add comic provider.
        """
        pass

    def test_delete_comic(self) -> None:
        """Test case for delete_comic

        Delete comic.
        """
        pass

    def test_delete_comic_provider(self) -> None:
        """Test case for delete_comic_provider

        Delete comic provider.
        """
        pass

    def test_get_comic(self) -> None:
        """Test case for get_comic

        Get comic.
        """
        pass

    def test_get_comic_provider(self) -> None:
        """Test case for get_comic_provider

        Get comic provider.
        """
        pass

    def test_list_comic(self) -> None:
        """Test case for list_comic

        List comic.
        """
        pass

    def test_list_comic_provider(self) -> None:
        """Test case for list_comic_provider

        List comic provider.
        """
        pass

    def test_update_comic(self) -> None:
        """Test case for update_comic

        Update comic.
        """
        pass

    def test_update_comic_provider(self) -> None:
        """Test case for update_comic_provider

        Update comic provider.
        """
        pass


if __name__ == '__main__':
    unittest.main()
