# coding: utf-8

"""
    ComicBagi

    Comic hosting catalog provider.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicbagi_openapi.models.set_comic import SetComic

class TestSetComic(unittest.TestCase):
    """SetComic unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetComic:
        """Test SetComic
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetComic`
        """
        model = SetComic()
        if include_optional:
            return SetComic(
                code = ''
            )
        else:
            return SetComic(
        )
        """

    def testSetComic(self):
        """Test SetComic"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
