# coding: utf-8

# flake8: noqa
"""
    ComicBagi

    Comic hosting catalog provider.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from comicbagi_openapi.models.comic import Comic
from comicbagi_openapi.models.comic_chapter import ComicChapter
from comicbagi_openapi.models.comic_chapter_provider import ComicChapterProvider
from comicbagi_openapi.models.comic_provider import ComicProvider
from comicbagi_openapi.models.error import Error
from comicbagi_openapi.models.language import Language
from comicbagi_openapi.models.link import Link
from comicbagi_openapi.models.new_comic import NewComic
from comicbagi_openapi.models.new_comic_chapter import NewComicChapter
from comicbagi_openapi.models.new_comic_chapter_provider import NewComicChapterProvider
from comicbagi_openapi.models.new_comic_provider import NewComicProvider
from comicbagi_openapi.models.new_language import NewLanguage
from comicbagi_openapi.models.new_link import NewLink
from comicbagi_openapi.models.new_website import NewWebsite
from comicbagi_openapi.models.set_comic import SetComic
from comicbagi_openapi.models.set_comic_chapter import SetComicChapter
from comicbagi_openapi.models.set_comic_chapter_provider import SetComicChapterProvider
from comicbagi_openapi.models.set_comic_provider import SetComicProvider
from comicbagi_openapi.models.set_language import SetLanguage
from comicbagi_openapi.models.set_link import SetLink
from comicbagi_openapi.models.set_website import SetWebsite
from comicbagi_openapi.models.website import Website
