# coding: utf-8

"""
    ComicBagi

    Comic hosting catalog provider.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SetComicChapterProvider(BaseModel):
    """
    SetComicChapterProvider
    """ # noqa: E501
    link_website_host: Optional[StrictStr] = Field(default=None, alias="linkWebsiteHost")
    link_relative_reference: Optional[StrictStr] = Field(default=None, alias="linkRelativeReference")
    language_lang: Optional[StrictStr] = Field(default=None, alias="languageLang")
    released_at: Optional[datetime] = Field(default=None, alias="releasedAt")
    __properties: ClassVar[List[str]] = ["linkWebsiteHost", "linkRelativeReference", "languageLang", "releasedAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SetComicChapterProvider from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if link_website_host (nullable) is None
        # and model_fields_set contains the field
        if self.link_website_host is None and "link_website_host" in self.model_fields_set:
            _dict['linkWebsiteHost'] = None

        # set to None if link_relative_reference (nullable) is None
        # and model_fields_set contains the field
        if self.link_relative_reference is None and "link_relative_reference" in self.model_fields_set:
            _dict['linkRelativeReference'] = None

        # set to None if language_lang (nullable) is None
        # and model_fields_set contains the field
        if self.language_lang is None and "language_lang" in self.model_fields_set:
            _dict['languageLang'] = None

        # set to None if released_at (nullable) is None
        # and model_fields_set contains the field
        if self.released_at is None and "released_at" in self.model_fields_set:
            _dict['releasedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SetComicChapterProvider from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "linkWebsiteHost": obj.get("linkWebsiteHost"),
            "linkRelativeReference": obj.get("linkRelativeReference"),
            "languageLang": obj.get("languageLang"),
            "releasedAt": obj.get("releasedAt")
        })
        return _obj


